"""Add billing reports table

Revision ID: 027ab7b6c6bf
Revises: e549f7317307
Create Date: 2026-06-29 17:41:37.485952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027ab7b6c6bf'
down_revision = 'e549f7317307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('total_services', sa.Integer(), nullable=False),
    sa.Column('highest_service', sa.String(length=100), nullable=False),
    sa.Column('highest_cost', sa.Float(), nullable=False),
    sa.Column('average_cost', sa.Float(), nullable=False),
    sa.Column('estimated_savings', sa.Float(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_reports')
    # ### end Alembic commands ###
